liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "images/cache"
    filter_sets:
        thumb:
            quality: 75
            filters:
                thumbnail:
                    size: [360, 260]
                    mode: outbound
                    allow_upscale: true
        medium:
            quality: 75
            filters:
                thumbnail:
                    size: [500, 500]
                    mode: outbound
                    allow_upscale: true
        tiny:
            quality: 75
            filters:
                thumbnail:
                    size: [35, 35]
                    mode: outbound
